### ISSUE TITLE
InvalidRecord error when latching header has zero bytes

### ISSUE THREAD

**Issue by jobafr** [newpavlov/rosbag-rs#4]
I just hunted down the exact same bug that I then realized @DomWilliamsEE has already [fixed in their fork](https://github.com/newpavlov/rosbag-rs/compare/master...DomWilliamsEE:rosbag-rs:master) of this crate.

Some connections  will not set `latching=0` or `latching=1`, but `latching=` (zero bytes). For me, this was the case for topics produced by a [rosrust](https://github.com/adnanademovic/rosrust/)-based node, though I'm unsure whether that is what's causing the issue.

If you have the time, it'd be great if you could merge DomWilliamsEE's fix and do a crates.io release :)

**Comment by newpavlov** [comment]
See discussion in #2. We concluded that such files should be considered incorrect according to the rosbag format "spec". I could reconsider this decision, but ideally it should be fixed on the generation side.

**Comment by jobafr** [comment]
Hi, yeah, I understand the argument — in our case however, the faulty bag was produced by ROS noetic's rosbag. Given the general state of ROS1 maintenance, I think there is a good argument for aiming for bug-compatibility instead of spec-compatibility :upside_down_face:.

**Comment by jobafr** [comment]
thanks :)
